"""
pipeline/deduplicator.py
=========================
Phase 3 — Smart Job Deduplication

Implements two complementary deduplication mechanisms:

1. **SHA-256 Canonical Hashing** — generates a deterministic fingerprint
   for any (title, company, location) triple.  Identical jobs from
   different scrapers produce the same hash → exact deduplication.

2. **Bloom Filter** — a probabilistic, O(1) membership structure built
   from scratch using a ``bytearray`` bit-array and ``k`` independent
   hash functions (seeded via zlib.adler32 with different primes).
   Used as a cheap pre-check *before* a more expensive set/database lookup.

CS Background
-------------
* Bloom Filter: Burton H. Bloom (1970).  Space-efficient probabilistic
  data structure with zero false negatives and a tunable false-positive
  rate.  Time complexity: O(k) per insert/query, Space: O(m) bits.
* SHA-256: cryptographic hash via ``hashlib`` (FIPS 180-4).
"""

from __future__ import annotations

import hashlib
import logging
import math
import zlib

logger = logging.getLogger(__name__)


# ===========================================================================
# Bloom Filter
# ===========================================================================

class BloomFilter:
    """
    Space-efficient probabilistic set membership structure.

    Guarantees **zero false negatives** (if an item was inserted, it will
    always be detected).  Admits a small, configurable rate of
    **false positives** (items that were never inserted may occasionally
    appear as "maybe present").

    Implementation details
    ----------------------
    * Bit-array of size ``m`` bits backed by a ``bytearray``.
    * ``k`` independent hash functions generated by seeding ``zlib.adler32``
      with the first ``k`` prime numbers, then taking ``hash_value % m``.

    Parameters
    ----------
    capacity : int
        Expected number of items to store.
    false_positive_rate : float
        Desired maximum false-positive probability (0 < p < 1).
        Defaults to 1 % (0.01).

    Attributes
    ----------
    m : int
        Total number of bits.
    k : int
        Number of hash functions.
    """

    # First 10 primes used as hash-function seeds
    _PRIMES: tuple[int, ...] = (2, 3, 5, 7, 11, 13, 17, 19, 23, 29)

    def __init__(self, capacity: int = 10_000, false_positive_rate: float = 0.01) -> None:
        if not (0 < false_positive_rate < 1):
            raise ValueError("false_positive_rate must be between 0 and 1 (exclusive).")
        if capacity < 1:
            raise ValueError("capacity must be at least 1.")

        # Optimal bit-array size: m = -n * ln(p) / (ln 2)^2
        self.m: int = math.ceil(
            -capacity * math.log(false_positive_rate) / (math.log(2) ** 2)
        )
        # Optimal number of hash functions: k = (m / n) * ln 2
        self.k: int = max(1, round((self.m / capacity) * math.log(2)))

        # Clamp k to the number of available prime seeds
        self.k = min(self.k, len(self._PRIMES))

        self._bits: bytearray = bytearray(math.ceil(self.m / 8))
        self._count: int = 0

        logger.debug(
            "[BloomFilter] Initialised: capacity=%d fpr=%.3f m=%d bits k=%d hash functions",
            capacity, false_positive_rate, self.m, self.k,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _bit_positions(self, item: str) -> list[int]:
        """
        Compute the ``k`` bit positions for *item*.

        Each position is derived from ``zlib.adler32(seed_bytes + item_bytes) % m``
        where ``seed_bytes`` is a different prime for each of the k functions.
        This gives k statistically independent hash functions without external libs.
        """
        item_bytes = item.encode("utf-8")
        positions: list[int] = []
        for i in range(self.k):
            seed = self._PRIMES[i].to_bytes(4, "big")
            raw = zlib.adler32(seed + item_bytes) & 0xFFFFFFFF
            positions.append(raw % self.m)
        return positions

    def _set_bit(self, pos: int) -> None:
        byte_idx, bit_idx = divmod(pos, 8)
        self._bits[byte_idx] |= 1 << bit_idx

    def _get_bit(self, pos: int) -> bool:
        byte_idx, bit_idx = divmod(pos, 8)
        return bool(self._bits[byte_idx] & (1 << bit_idx))

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    def add(self, item: str) -> None:
        """
        Insert an item into the Bloom Filter.

        Parameters
        ----------
        item : str
            The string to insert (typically a job hash).
        """
        for pos in self._bit_positions(item):
            self._set_bit(pos)
        self._count += 1

    def might_contain(self, item: str) -> bool:
        """
        Test whether an item *might* be in the set.

        Returns
        -------
        bool
            ``False``  → item is **definitely** not in the set.
            ``True``   → item is **probably** in the set (may be a false positive).
        """
        return all(self._get_bit(pos) for pos in self._bit_positions(item))

    @property
    def count(self) -> int:
        """Approximate number of items inserted."""
        return self._count

    @property
    def estimated_false_positive_rate(self) -> float:
        """
        Current estimated false-positive rate based on the number of
        inserted items: (1 - e^(-k*n/m))^k.
        """
        if self._count == 0:
            return 0.0
        exponent = -(self.k * self._count) / self.m
        return (1 - math.exp(exponent)) ** self.k


# ===========================================================================
# Job Deduplicator
# ===========================================================================

class JobDeduplicator:
    """
    Deduplication engine for job listings.

    Combines two stages:
    1. **Bloom Filter pre-check** — O(1) probabilistic membership test.
       Eliminates obvious non-duplicates with no false negatives.
    2. **SHA-256 exact hash** — deterministic fingerprint stored in an
       in-memory set for exact-match confirmation.

    Workflow::

        hash = deduplicator.generate_hash(title, company, location)
        if not deduplicator.is_duplicate(hash):
            deduplicator.mark_seen(hash)
            # → process and store the job
        else:
            # → skip (already seen)

    Parameters
    ----------
    bloom_capacity : int
        Expected number of unique jobs (configures Bloom Filter sizing).
    bloom_fpr : float
        Desired Bloom Filter false-positive rate.
    """

    def __init__(
        self,
        bloom_capacity: int = 10_000,
        bloom_fpr: float = 0.01,
    ) -> None:
        self._bloom: BloomFilter = BloomFilter(bloom_capacity, bloom_fpr)
        self._seen: set[str] = set()  # exact hash store

    @staticmethod
    def generate_hash(title: str, company: str, location: str) -> str:
        """
        Generate a canonical SHA-256 fingerprint for a job listing.

        Inputs are normalised (lowercased, whitespace-collapsed) before
        hashing so that minor formatting differences don't create false
        duplicates:

        * ``"  Python Dev  "`` == ``"python dev"``
        * ``"Google Inc."`` == ``"google inc."``

        Parameters
        ----------
        title : str
            Job title string.
        company : str
            Company name string.
        location : str
            Job location string.

        Returns
        -------
        str
            64-character lowercase hex SHA-256 digest.
        """
        def _normalise(s: str) -> str:
            import re
            return re.sub(r"\s+", " ", s.strip().lower())

        canonical = f"{_normalise(title)}|{_normalise(company)}|{_normalise(location)}"
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    def is_duplicate(self, job_hash: str) -> bool:
        """
        Check whether a job hash has been seen before.

        Uses the Bloom Filter as a fast pre-filter.  Only performs the
        slower exact-set lookup when the Bloom Filter says "maybe".

        Parameters
        ----------
        job_hash : str
            A hash previously returned by ``generate_hash``.

        Returns
        -------
        bool
            ``True`` if the job is a confirmed duplicate.
            ``False`` if it is definitely new.
        """
        if not self._bloom.might_contain(job_hash):
            # Bloom Filter guarantees no false negatives → definitely new
            logger.debug("[Deduplicator] Bloom says 'no' for hash %s…", job_hash[:12])
            return False

        # Bloom Filter said "maybe" → check exact set
        result = job_hash in self._seen
        logger.debug(
            "[Deduplicator] Exact set check for hash %s… → %s",
            job_hash[:12],
            "DUPLICATE" if result else "new (bloom false-positive)",
        )
        return result

    def mark_seen(self, job_hash: str) -> None:
        """
        Record a job hash as processed.

        Parameters
        ----------
        job_hash : str
            Hash to add to both the Bloom Filter and the exact store.
        """
        self._bloom.add(job_hash)
        self._seen.add(job_hash)
        logger.debug("[Deduplicator] Marked hash %s… as seen.", job_hash[:12])

    @property
    def seen_count(self) -> int:
        """Number of unique jobs processed."""
        return len(self._seen)
